import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from "/styles/Home.module.css";
import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore, collection, getDocs } from "firebase/firestore";


////////////////////////////////////////////////


/////////////////////////////////////////////////////////



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>筆記分享區</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.group}>
          <div className={styles.introduce}>
            <img src="pic/welcome.png" width="300px" />


            <a href="https://nextjs.org/docs" className={styles.post}>
              <p>先看看其他文章 &rarr;</p>
            </a>

          </div>

          <div className={styles.logincon}>
            <p className={styles.emailpass}>常用信箱：</p>
            <input className={styles.enter} type="text" name="email" placeholder="請輸入信箱..." />
            <p className={styles.emailpass}>密碼：</p>
            <input className={styles.enter} type="password" name="password" placeholder="請輸入密碼..." /><br />
            <input className={styles.loginbtn} type="submit" value="登入" name="submit" /><br />
            <a href="">忘記密碼</a><br />
            <p>沒有帳號？現在就加入我們吧！</p>
            <h4><a href="register.php">點此註冊</a></h4>
          </div>
        </div>
      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
