import React, {useState} from 'react';
import Head from 'next/head';
import Image from 'next/image';
import {Button, TextField} from '@mui/material';
import { getApps, initializeApp } from "firebase/app";
import { getAuth, createUserWithEmailAndPassword,updateProfile } from "firebase/auth";
import {firebaseConfig} from '../../settings/firebaseConfig';
import styles from "/styles/Home.module.css";
import myImage from '../../public/pic/welcome.png';
import Link from 'next/link';




export default function SignUp() {
  if (getApps().length===0) {
    initializeApp(firebaseConfig);
  }
  const [account, setAccount] = useState({email:"",password:"", password2:"" , displayName:""});
  const [message, setMessage] = useState("");
  const handleChange = function (e: { target: { name: any; value: any; }; }) {
    setAccount({...account,[e.target.name]:e.target.value})
  }
  const handleSubmit = async function(){

    try {
      const auth = getAuth();
      const res = await createUserWithEmailAndPassword(auth, account.email, account.password);
      if (res) {
        await updateProfile(res.user,{displayName: account.displayName});
      }
      setMessage("");

    }
    catch(error){
      setMessage(""+error);
    }

    
  }
  
  return(
    
    <div className={styles.container}>
       <Head>
       <title>Line log in</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main_re}>
        <div>
          <Button className={styles.Line_login_btn} type="submit">Log in with Line</Button>

        </div>

       </main>


       
     </div>

    


        
  )
}
