import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
      <title>新增文章</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      <div className={styles.addArticle_container}>
          <div className={styles.addArticle_bar}>
            <div className={styles.user_box}>
            <div><img className="user_image" src="pic/test1.jpeg"/></div>
              <div className={styles.user_name}>
              </div>
            </div>
          </div>
      </div>

        <div className={styles.grid}>
        <div><textarea className={styles.addArticle_contectTitle} placeholder="請輸入文章標題..." name="title"></textarea> </div>
          <div contentEditable="true" className={styles.addArticle_content} placeholder="請輸入文章內容..." name="content"></div>
            <input className={styles.enter} style="position:absolute; width:15%;" placeholder="筆記標籤"/>
        </div>

        <div className={styles.addArticle_function}></div>
        <div className={styles.upload_file}></div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
