import Head from 'next/head';
import Navbar from '../../components/navbar/Navbar';
import magicCat from '../../public/pic/magicCat.png';
import WishListItem from '@/components/wish/WishListItem';

//mui
import { styled } from '@mui/material/styles';
import { Container } from '@mui/material';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Avatar from '@mui/material/Avatar';
import CardHeader from '@mui/material/CardHeader';
import ButtonBase from '@mui/material/ButtonBase';
import Button from '@mui/material/Button';
import Image from 'next/image';

import { red } from '@mui/material/colors';
import LocalFireDepartmentIcon from '@mui/icons-material/LocalFireDepartment';
import styles from '../../styles/Home.module.css';



const Item = styled(Paper)(({ theme }) => ({
   //backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
   backgroundColor: '#ffffff',
   ...theme.typography.body2,
   margin: theme.spacing(2),
   padding: theme.spacing(1),
   textAlign: 'center',
   color: theme.palette.text.secondary,
}));

// 星星動畫 //
interface StarProps {
   x: number;
   y: number;
}

const Star: React.FC<StarProps> = ({ x, y }) => {
   return <div className={styles.star} style={{ left: `${x}px`, top: `${y}px` }}></div>;
};

const getRandomPosition = () => {
   const x = Math.random() * 260; // 0 to 280 (300 - star width)
   const y = Math.random() * 260; // 0 to 280 (300 - star height)
   return { x, y };
};
//New wish
const Newwish = () => {
   const numStars = 30; // 星星的數量
   const stars = Array.from({ length: numStars }, (_, index) => {
      const { x, y } = getRandomPosition();
      return <Star key={index} x={x} y={y} />;
   });
   return (
      <Grid item direction='column'>
         <Grid item xs={8}>
            <Paper
               sx={{
                  width: 330,
                  height: 'auto',
                  margin: 'auto',
                  flexGrow: 1,
               }}
            >
               <div style={{
                  position: 'relative',
                  height: 280,
                  borderTopLeftRadius: 5,
                  borderTopRightRadius: 5,
                  backgroundColor: '#425E99',
               }}>

                  {stars}
                  <Image src={magicCat} height='900' />
               </div>
               <Box sx={{ p: 2, }}>
                  <Typography variant="body2" gutterBottom >
                     找不到想看的內容嗎？試著在這裡許下願望，讓願望藉由大家的力量實現吧！
                  </Typography>
                  <Typography
                     variant="button"
                     display="block"
                     gutterBottom
                     sx={{
                        cursor: 'pointer',
                        textAlign: 'center',
                        color: '#425E99',
                        mt: 2
                     }}
                  >
                     Make a wish
                  </Typography>

               </Box>

            </Paper>
         </Grid>
      </Grid>
   )
}


//wishes
const renderWish = () => {
   return (
      <WishListItem />
   );

};



const WishingPool = () => {
   return (
      <div>
         <Head>
            <title>許願池</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" ></meta>
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Navbar />
         <Toolbar />
         <Container>
            <Grid
               xs={12}
               mt={5}
               container
               flexDirection={{ xs: 'column', sm: 'row' }}
               sx={{ fontSize: '12px' }}
               spacing={2}
            >
               <Grid item container xs={12} md={4} direction='column'>
                  <Newwish />
               </Grid>
               <Grid item xs={12} md={8}>
                  <WishListItem />
               </Grid>
            </Grid>
         </Container>
      </div>
   )

};
export default WishingPool;