import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from "/styles/Home.module.css";
import Link from 'next/link'
import { Button, TextField, Container, Autocomplete, Stack, Box } from '@mui/material';



<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
  crossOrigin="anonymous"
/>


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>新增筆記</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ padding: 5, borderRadius: 4, background: 'white', width: 0.6 }}>

        <img className={styles.user_image} src="pic/test1.jpeg" />

        <Box sx={{margin: 4, }}>
          <TextField id="outlined-basic" label="請輸入文章標題" variant="outlined" /><br />
          <TextField
            id="outlined-multiline-static"
            label="請輸入文章內容"
            multiline
            fullWidth
            rows={10}
            margin="normal"
            
          /><br />
          <Button color="primary" ><input multiple type="file" /></Button>

          <div>
            <Button variant="contained" >發布</Button>
            <Button variant="contained">取消</Button>
          </div>
        </Box>


      </Container>



      

      {/* <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer> */}
    </div>
  )




}





export default Home
