import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from "/styles/Home.module.css";
import Link from 'next/link'
import { Button, TextField } from '@mui/material';

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
  crossOrigin="anonymous"
/>

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>新增筆記</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.addArticle_container}>
          <div className={styles.addArticle_bar}>
            <div className={styles.user_box}>
              <div><img className={styles.user_image} src="pic/test1.jpeg" />
                <div className={styles.user_name}>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.grid}>
            <div>
              <div><textarea className={styles.addArticle_contectTitle} placeholder="請輸入文章標題..." name="title"></textarea>
                <textarea name="Content" style={{ width: "800px", height: "400px" }} placeholder="請輸入文章內容..." ></textarea>
                <br></br>
                <input className={styles.enter} style={{ width: '20%' }} placeholder="請輸入筆記標籤..." />
                
                <div className="container">
                  <div className="row">
                    <div className="col-sm">
                      <div className={styles.addArticle_function_btn}>

                        <h4><Button variant="contained" color="primary" ><input multiple type="file" /></Button></h4>
                        <Button><input multiple type="file" /></Button>

                        <h4><Button variant="contained" color="primary" >取消</Button></h4>
                        <h4><Button variant="contained" color="primary">發布</Button></h4>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>





        </div>

      </main>

      {/* <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer> */}
    </div>
  )
}

export default Home
