import * as React from 'react';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Navbar from '../../components/navbar/Navbar';
import Head from 'next/head';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import { spacing } from '@material-ui/system';
import { makeStyles } from '@material-ui/core/styles';
import Chip from '@material-ui/core/Chip';
import EditIcon from '@material-ui/icons/Edit';
import { Avatar } from '@mui/material';
import { bgcolor } from '@mui/system';
import { createTheme } from '@material-ui/core/styles';
import Divider from '@mui/material/Divider';
import Toolbar from '@mui/material/Toolbar';
import Stack from '@mui/material/Stack';


//chip的style
const useStyles = makeStyles((theme) => ({
  root: {
    display: 'flex',
    justifyContent: 'center',
    flexWrap: 'wrap',
    '& > *': {
      margin: theme.spacing(0.5),
    },
  },
}));


export default function profile() {
  const theme = createTheme({
    spacing: 4,
  });



  return (
    <div>
      <div>
        <Head>
          <title>我的角色</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>


      <Navbar />
      <div>
        <Container >
          <Toolbar />
          <br />
          <Card>

            <Box sx={{ bgcolor: '#ffffff' }}>
              {/* <Box sx={{ bgcolor: '#BCD4DE', height: '100vh', }}> */}
              <Box p={1.5}>
                <Typography fontSize={20}>個人資料</Typography>
              </Box>

              <Divider />

              <Box display="flex" p={2} justifyContent={'space-between'} flexDirection='row'>

                <Box width={0.3} bgcolor={'#ffffff'}>
                  <Box>
                    <Box display="flex">
                      <Box pr={3}>
                        <Avatar
                          sx={{
                            width: 70,
                            height: 70,
                          }}
                        >
                          H
                        </Avatar>
                      </Box>
                      <Box>
                        <Typography pt={0.8} fontSize={25} >user</Typography>
                        <Typography fontSize={12}>@userid</Typography>
                      </Box>
                    </Box>
                    <Box m={1}>
                      聯絡資訊
                    </Box>
                  </Box>
                </Box>

                <Box width={0.4} bgcolor={'#fafafa'} >
                  <Card>
                    {/* <Card sx={{ minWidth: 275 }}> */}
                    <CardContent>
                      <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom>
                        擅長領域：
                      </Typography>
                      <Stack direction="row" spacing={1}>
                        <Chip label="tag 1" component="a" href="#chip" clickable />
                        <Chip label="tag 2" component="a" href="#chip" clickable />
                        <Chip label="tag 3" component="a" href="#chip" clickable />
                      </Stack>
                    </CardContent>
                  </Card>
                </Box>

                <Box display="flex">
                  <EditIcon
                    style={{
                      fontSize: 30,
                      color: "#7A82E7",

                    }}
                  />
                </Box>

              </Box>
            </Box>
          </Card>
        </Container>
      </div>

    </div >





  );
}