import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import styles from "/styles/Home.module.css";
import Button from 'react-bootstrap/Button';

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
  crossOrigin="anonymous"
/>

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>文章內容</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.article_container}>
          <div className={styles.addArticle_bar}>
            <div className={styles.user_box}>
              <div><img className={styles.user_image} src="pic/test1.jpeg" />
                <div className={styles.user_name}>
                </div>
              </div>
            </div>
          </div>


          <div className={styles.article_items_container}>
            <h2>title</h2><br />
            <p>content</p>
          </div>


          <div className={styles.article_toolbar}>
            <div className={styles.article_function_btn}>
              <button className={styles.article_btn} type="submit">愛心</button>
              <button className={styles.article_btn} type="submit">儲存</button>
              <button className={styles.article_btn} type="submit">分享</button>
            </div>
          </div>


        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
