import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
      <title>筆記分享區</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>Angel</h2> */}

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>爬蟲實作教學</h2>
            <p>Python網路爬蟲就是利用撰寫Python程式碼去對網路資訊進行擷取，例如蒐集匯率的歷史走勢、熱門議題的輿情...等等</p>
            <div className={styles.card2}>
              <p>victoria</p>
            </div>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>java物件導向筆記</h2>
            <p>一般來說，討及「物件導向」（object-oriented）總是會提供及：物件、抽象、封裝、繼承、多型等 關於封裝 在解釋封裝概念之前，我們先得來解釋什麼是「...</p>
            <div className={styles.card2}>
              <p>EvonnePeng</p>
            </div>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>title</h2>
            <p>content</p>
            <div className={styles.card2}>
              <p>user</p>
            </div>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>title</h2>
            <p>content</p>
            <div className={styles.card2}>
              <p>user</p>
            </div>
          </a>
        </div>

      </main>
    </div>
  )
}

export default Home
